version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    volumes:
      - "{{ dirs.state }}/portainer:/data"
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "{{ ports.portainer_http }}:8000"
      - "{{ ports.portainer_https }}:9443"
    restart: unless-stopped

  ddclient:
    container_name: ddclient
    image: linuxserver/ddclient
    environment:
      TZ: "{{ tz }}"
    volumes:
      - "/home/docker/ddclient.conf:/config/ddclient.conf"
    restart: unless-stopped

  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing:latest
    environment:
      PUID: "{{ users.syncthing.uid }}"
      GUID: "{{ users.syncthing.uid }}"
      TZ: "{{ tz }}"
    volumes:
      - "{{ dirs.state }}/syncthing:/config"
      - "{{ dirs.files }}:/files"
    ports:
      - "{{ ports.syncthing }}:8384"
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: "{{ tz }}"
      WEBPASSWORD: "{{ pihole_passwd }}"
    volumes:
      - "{{ dirs.state }}/pihole/etc:/etc/pihole"
      - "{{ dirs.state }}/pihole/dnsmasq.d:/etc/dnsmasq.d"
    ports:
      - "192.168.1.20:53:53/tcp"
      - "192.168.1.20:53:53/udp"
      - "{{ ports.pihole }}:80/tcp"
    restart: unless-stopped

  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "{{ ports.pl3xmap }}:8080"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.20.1"
      MEMORY: "8G"
      USE_AIKAR_FLAGS: "true"
      ENABLE_ROLLING_LOGS: "true"
      TZ: "{{ tz }}"
      DIFFICULTY: "hard"
      SEED: "14358270646322246249"
      ALLOW_FLIGHT: "true"
      ENFORCE_SECURE_PROFILE: "false"
      WHITELIST: |-
        Tyraeis
      OPS: |-
        Tyraeis
      CF_API_KEY: '{{ curseforge_api_key | replace("$", "$$") }}'
      CURSEFORGE_FILES: |-
        architectury-api
        polylib
        ftb-backups-2
      MODRINTH_PROJECTS: |-
        fabric-api
        fabric-language-kotlin
        lithium
        sodium
        ferrite-core
        starlight
        memoryleakfix
        krypton
        no-chat-reports
        carpet
        chunky
        ledger
        pl3xmap:beta
      RCON_CMDS_STARTUP: |-
        chunky radius 10000
        chunky spawn
        chunky start
        chunky continue

        chunky world world_nether
        chunky radius 5000
        chunky spawn
        chunky start
        chunky continue

        chunky world world_the_end
        chunky radius 5000
        chunky spawn
        chunky start
        chunky continue
      RCON_CMDS_FIRST_CONNECT: |-
        chunky pause
      RCON_CMDS_LAST_DISCONNECT: |-
        chunky continue
    volumes:
      - "{{ dirs.state }}/minecraft/data:/data"
      - "{{ dirs.files }}/www/minecraft/backups:/backups"
